name: rohossholok
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^9.1.1
  
  # HTTP Client
  dio: ^5.9.0
  
  # Navigation
  go_router: ^16.1.0
  
  # HTML Rendering
  flutter_html: ^3.0.0-beta.2
  
  # Image Caching
  cached_network_image: ^3.3.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # JSON Serialization
  json_annotation: ^4.9.0
  
  # Code Generation
  freezed_annotation: ^3.1.0
  
  # Utilities
  intl: ^0.20.2
  equatable: ^2.0.5
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  freezed: ^3.2.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
